import { db, settingsTable, syllabusTable, testsTable } from "@workspace/db";

export const SYLLABUS_CHAPTERS: { subject: string; track: string; chapter: string }[] = [
  // Physics Track 01
  { subject: "Physics", track: "01", chapter: "Vectors" },
  { subject: "Physics", track: "01", chapter: "Rectilinear Motion" },
  { subject: "Physics", track: "01", chapter: "Projectile Motion" },
  { subject: "Physics", track: "01", chapter: "Relative Motion" },
  { subject: "Physics", track: "01", chapter: "Circular Kinematics" },
  { subject: "Physics", track: "01", chapter: "Work, Power, and Energy" },
  { subject: "Physics", track: "01", chapter: "COM, Momentum, and Collision" },
  { subject: "Physics", track: "01", chapter: "Rigid Body Mechanics" },
  { subject: "Physics", track: "01", chapter: "Simple Harmonic Motion" },
  { subject: "Physics", track: "01", chapter: "Gravitation" },
  // Physics Track 02
  { subject: "Physics", track: "02", chapter: "Basic Mathematics" },
  { subject: "Physics", track: "02", chapter: "Units and Measurements, Errors, and Experiments" },
  { subject: "Physics", track: "02", chapter: "Newton's Laws of Motion" },
  { subject: "Physics", track: "02", chapter: "Mechanical Properties of Solids (Elasticity)" },
  { subject: "Physics", track: "02", chapter: "Thermometry" },
  { subject: "Physics", track: "02", chapter: "Thermal Expansion" },
  { subject: "Physics", track: "02", chapter: "Calorimetry" },
  { subject: "Physics", track: "02", chapter: "Heat Transfer" },
  { subject: "Physics", track: "02", chapter: "Kinetic Theory of Gases" },
  { subject: "Physics", track: "02", chapter: "Thermodynamics" },
  { subject: "Physics", track: "02", chapter: "Fluid Mechanics" },
  { subject: "Physics", track: "02", chapter: "Transverse Waves (String Waves)" },
  { subject: "Physics", track: "02", chapter: "Longitudinal Waves (Sound Waves)" },
  // Chemistry Track 01
  { subject: "Chemistry", track: "01", chapter: "Atomic Structure" },
  { subject: "Chemistry", track: "01", chapter: "Chemical Bonding" },
  { subject: "Chemistry", track: "01", chapter: "Gaseous States" },
  { subject: "Chemistry", track: "01", chapter: "Liquids" },
  { subject: "Chemistry", track: "01", chapter: "Thermodynamics" },
  { subject: "Chemistry", track: "01", chapter: "Thermochemistry" },
  { subject: "Chemistry", track: "01", chapter: "Chemical Equilibrium" },
  { subject: "Chemistry", track: "01", chapter: "Ionic Equilibrium" },
  { subject: "Chemistry", track: "01", chapter: "Redox Reactions" },
  { subject: "Chemistry", track: "01", chapter: "Equivalent Concept and Volumetric Analysis" },
  // Chemistry Track 02
  { subject: "Chemistry", track: "02", chapter: "Some Basic Concepts of Chemistry (Mole Concept)" },
  { subject: "Chemistry", track: "02", chapter: "Periodic Classification" },
  { subject: "Chemistry", track: "02", chapter: "IUPAC Nomenclature" },
  { subject: "Chemistry", track: "02", chapter: "Physical Properties, Qualitative and Quantitative Analysis" },
  { subject: "Chemistry", track: "02", chapter: "GOC-I" },
  { subject: "Chemistry", track: "02", chapter: "GOC-II" },
  { subject: "Chemistry", track: "02", chapter: "Stereochemistry" },
  { subject: "Chemistry", track: "02", chapter: "Hydrocarbons" },
  { subject: "Chemistry", track: "02", chapter: "Hydrogen" },
  { subject: "Chemistry", track: "02", chapter: "s-Block Elements" },
  { subject: "Chemistry", track: "02", chapter: "Environmental Chemistry" },
  { subject: "Chemistry", track: "02", chapter: "p-Block Elements" },
  // Maths Track 01
  { subject: "Maths", track: "01", chapter: "Basic Maths" },
  { subject: "Maths", track: "01", chapter: "Trigonometric Ratios and Identities" },
  { subject: "Maths", track: "01", chapter: "Trigonometric Equations and Inequalities" },
  { subject: "Maths", track: "01", chapter: "Properties of Triangles" },
  { subject: "Maths", track: "01", chapter: "Introduction to Co-ordinate Geometry" },
  { subject: "Maths", track: "01", chapter: "Straight Lines" },
  { subject: "Maths", track: "01", chapter: "Introduction to 3D Geometry" },
  { subject: "Maths", track: "01", chapter: "Pair of Lines" },
  { subject: "Maths", track: "01", chapter: "Circles" },
  { subject: "Maths", track: "01", chapter: "Conic Sections" },
  { subject: "Maths", track: "01", chapter: "Statistics" },
  { subject: "Maths", track: "01", chapter: "Limits" },
  { subject: "Maths", track: "01", chapter: "Methods of Differentiation" },
  // Maths Track 02
  { subject: "Maths", track: "02", chapter: "Sets" },
  { subject: "Maths", track: "02", chapter: "Relations" },
  { subject: "Maths", track: "02", chapter: "Introduction to Functions" },
  { subject: "Maths", track: "02", chapter: "Linear Inequalities" },
  { subject: "Maths", track: "02", chapter: "Fundamentals of Mathematics" },
  { subject: "Maths", track: "02", chapter: "Quadratic Equations and Expressions" },
  { subject: "Maths", track: "02", chapter: "Sequence and Series" },
  { subject: "Maths", track: "02", chapter: "Binomial Theorem" },
  { subject: "Maths", track: "02", chapter: "Permutations and Combinations" },
  { subject: "Maths", track: "02", chapter: "Functions" },
  { subject: "Maths", track: "02", chapter: "Probability" },
];

export const TEST_TEMPLATES: { name: string; date: string; time: string; type: string; notes: string | null }[] = [
  { name: "Weekly Test - Physics 1", date: "2026-04-27", time: "09:00", type: "coaching", notes: null },
  { name: "Weekly Test - Chemistry 1", date: "2026-05-04", time: "09:00", type: "coaching", notes: null },
  { name: "Weekly Test - Maths 1", date: "2026-05-11", time: "09:00", type: "coaching", notes: null },
  { name: "Main Test 1", date: "2026-05-24", time: "09:00", type: "mock", notes: null },
  { name: "Weekly Test - Physics 2", date: "2026-06-01", time: "09:00", type: "coaching", notes: null },
  { name: "Weekly Test - Chemistry 2", date: "2026-06-08", time: "09:00", type: "coaching", notes: null },
  { name: "Main Test 2", date: "2026-06-21", time: "09:00", type: "mock", notes: null },
  { name: "Weekly Test - Maths 2", date: "2026-06-29", time: "09:00", type: "coaching", notes: null },
  { name: "Weekly Test - Physics 3", date: "2026-07-06", time: "09:00", type: "coaching", notes: null },
  { name: "Main Test 3", date: "2026-07-19", time: "09:00", type: "mock", notes: null },
  { name: "Advanced Test 1 (One paper)", date: "2026-07-19", time: "14:00", type: "jee", notes: "One paper" },
  { name: "Weekly Test - Chemistry 3", date: "2026-07-27", time: "09:00", type: "coaching", notes: null },
  { name: "1st Quarterly Exam & CET-1", date: "2026-08-03", time: "09:00", type: "school", notes: "3 Aug – 7 Aug 2026" },
  { name: "Main Test 4", date: "2026-08-23", time: "09:00", type: "mock", notes: null },
  { name: "Advanced Test 2 (One paper)", date: "2026-08-23", time: "14:00", type: "jee", notes: "One paper" },
  { name: "Weekly Test - Maths 3", date: "2026-08-31", time: "09:00", type: "coaching", notes: null },
  { name: "Weekly Test - Physics 4", date: "2026-09-07", time: "09:00", type: "coaching", notes: null },
  { name: "Main Test 5", date: "2026-09-19", time: "09:00", type: "mock", notes: null },
  { name: "Advanced Test 3 (Two papers)", date: "2026-09-20", time: "09:00", type: "jee", notes: "Two papers" },
  { name: "Midterm Exam & CET-2", date: "2026-09-25", time: "09:00", type: "school", notes: "25 Sep – 9 Oct 2026" },
  { name: "Weekly Test - Chemistry 4", date: "2026-11-02", time: "09:00", type: "coaching", notes: null },
  { name: "Main Test 6", date: "2026-11-21", time: "09:00", type: "mock", notes: null },
  { name: "Advanced Test 4 (Two papers)", date: "2026-11-22", time: "09:00", type: "jee", notes: "Two papers" },
  { name: "Weekly Test - Maths 4", date: "2026-11-30", time: "09:00", type: "coaching", notes: null },
  { name: "2nd Quarterly Exam & CET-3", date: "2026-12-10", time: "09:00", type: "school", notes: "10 Dec – 15 Dec 2026" },
  { name: "Weekly Test - Physics 5", date: "2026-12-21", time: "09:00", type: "coaching", notes: null },
  { name: "Main Test 7", date: "2027-01-02", time: "09:00", type: "mock", notes: null },
  { name: "Advanced Test 5 (Two papers)", date: "2027-01-03", time: "09:00", type: "jee", notes: "Two papers" },
  { name: "Weekly Test - Chemistry 5", date: "2027-01-11", time: "09:00", type: "coaching", notes: null },
  { name: "Weekly Test - Maths 5", date: "2027-01-18", time: "09:00", type: "coaching", notes: null },
  { name: "Main Test 8", date: "2027-01-27", time: "09:00", type: "mock", notes: null },
  { name: "Advanced Test 6 (Two papers)", date: "2027-01-28", time: "09:00", type: "jee", notes: "Two papers" },
];

export async function seedNewUserData(userId: number) {
  await Promise.all([
    db.insert(settingsTable).values({
      userId,
      theme: "dark",
      accentColor: "#4aff00",
      jeeMainDate: "2027-01-22",
      jeeAdvancedDate: "2027-05-18",
    }),
    db.insert(syllabusTable).values(
      SYLLABUS_CHAPTERS.map((c) => ({ ...c, userId, status: "not_started" as const })),
    ),
    db.insert(testsTable).values(
      TEST_TEMPLATES.map((t) => ({ ...t, userId })),
    ),
  ]);
}
